spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: route_sg
          uri: https://segmentfault.com/
          predicates:
            - Path=/blogs


server:
  port: 8080



management:
  endpoints:
    web:
      exposure:
        include: '*'
